server:
  port: 8085

slack:
  base-url: https://hooks.slack.com
  channel:
    noti:

queue:
  exchange: topic-exchange
  tasks:
    - name: slack-queue
      routing-key:
        condition: slack.#
        warning: slack.warning
        alert: slack.alert
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1234

logging:
  config: classpath:log4j2.xml