url:
  bithumb:
    base: https://api.bithumb.com
    user:
      info: /info/account
      transactions: /info/user_transactions
      orders: /info/orders
      order-detail: /info/order_detail
    exchange:
      withdraw-minimum: /public/withdraw/minimum
      ticker: /public/ticker
      status: /public/assetsstatus/multichain
      network: /public/network-info
      trade: /trade/place
      orderBook: /public/orderbook
      price: /public/ticker

