url:
  bithumb:
    base: https://api.bithumb.com
    user:
      info: /info/account
      transactions: /info/user_transactions
      orders: /info/orders
      order-detail: /info/order_detail
    exchange:
      ticker: /public/ticker
      status: /public/assetsstatus/multichain
      network: /public/network-info