server:
  port: 8083

scheduler:
  daily-check: 0 0 0 * * *
  hourly-check: 0 0 * * * *
  minute-check: 0 * * * * *
  sec-check: 0/10 * * * * *

queue:
  name: sch-queue
  exchange: topic-exchange
  routing-key:
    condition: sch.exchange.#
    balance: sch.exchange.balance
    network: sch.exchange.network
    currency: sch.exchange.currency

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1234

logging:
  config: classpath:log4j2.xml