server:
  port: 8083

scheduler:
  cron: "* 0/1 * * * *"

api:
    base-url: http://localhost:8080
    endpoint:
      price: /price
spring:
  datasource:
    url: jdbc:h2:file:~/testdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true