server:
  port: 8082

api:
  bithumb:
    secret-key: 
    name: BITHMB-API
    base-url: http://localhost:8080
  upbit:
    name: UPBIT-API
    secret-key:
    base-url: http://localhost:8084
  endpoint:
    price: /price
    network: /network
    currency: /currency
    balance: /info/balance

queue:
  exchange: topic-exchange
  tasks:
    - name: sch-queue
      routing-key:
        condition: sch.exchange.#
        balance: sch.exchange.balance
        network: sch.exchange.network
        currency: sch.exchange.currency
    - name: slack-queue
      routing-key:
        condition: slack.#
        warning: slack.warning
        alert: slack.alert

spring:
  datasource:
    url: jdbc:h2:file:~/testdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1234

logging:
  config: classpath:log4j2.xml