server:
  port: 8082

api:
  bithumb:
    secret-key: 
    base-url: http://localhost:8080
    endpoint:
      price: /price
      network-status: /status
      balance: /info/balance

queue:
  name: "sch-queue"
  exchange: "sch-exchange"
  routing-key:
    condition: "sch.exchange.#"
    balance: "sch.exchange.balance"
    network: "sch.exchange.network"

spring:
  datasource:
    url: jdbc:h2:file:~/testdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1234

logging:
  config: classpath:log4j2.xml